spring:
  application:
    name: tanzu-devslam-spring

management:
  endpoints:
    web:
      exposure:
        # Enable actuator endpoints for health status and Prometheus metrics:
        # see /actuator/health and /actuator/prometheus.
        include: health, prometheus
  endpoint:
    health:
      probes:
        # Enable liveness and readiness probes (only running in Kubernetes by default):
        # see /actuator/health/liveness and /actuator/health/readiness.
        enabled: true

server:
  # You can override the server port using an environment variable.
  port: ${PORT:8080}
  # Enable graceful shutdown.
  shutdown: graceful

app:
  # Customizable app greetings message.
  message: Greetings from Spring Boot + Tanzu!
